// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3EjaML-wgoO6uHRmIj7s9IVgn9HpdbjY',
    appId: '1:919431182088:web:7888b9f29aba04d8201ebd',
    messagingSenderId: '919431182088',
    projectId: 'socialhivepretice',
    authDomain: 'socialhivepretice.firebaseapp.com',
    storageBucket: 'socialhivepretice.appspot.com',
    measurementId: 'G-0F4WZHJM8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgRTxxkQ8ThN0j-W05Yi2R3epMrctT0Ag',
    appId: '1:919431182088:android:d57b5b9093ae15a6201ebd',
    messagingSenderId: '919431182088',
    projectId: 'socialhivepretice',
    storageBucket: 'socialhivepretice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGRNWpOgKXMvxthyqQSgnhNF0p_II2ZI8',
    appId: '1:919431182088:ios:e4c3475f3ad9929f201ebd',
    messagingSenderId: '919431182088',
    projectId: 'socialhivepretice',
    storageBucket: 'socialhivepretice.appspot.com',
    iosBundleId: 'com.example.socialhiveDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGRNWpOgKXMvxthyqQSgnhNF0p_II2ZI8',
    appId: '1:919431182088:ios:e4c3475f3ad9929f201ebd',
    messagingSenderId: '919431182088',
    projectId: 'socialhivepretice',
    storageBucket: 'socialhivepretice.appspot.com',
    iosBundleId: 'com.example.socialhiveDart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3EjaML-wgoO6uHRmIj7s9IVgn9HpdbjY',
    appId: '1:919431182088:web:d0e3a3168174784d201ebd',
    messagingSenderId: '919431182088',
    projectId: 'socialhivepretice',
    authDomain: 'socialhivepretice.firebaseapp.com',
    storageBucket: 'socialhivepretice.appspot.com',
    measurementId: 'G-R80S6GE0JG',
  );
}
